sudo: required

language: java

services:
  - docker

after_success:
  - docker network create --driver bridge group1
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network group1 mongo
  - docker build -t group1 .
  - docker run --network se-methods group1